global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ontology'
    static_configs:
      - targets: ['ontology:8081']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8088']

  - job_name: 'registry'
    static_configs:
      - targets: ['registry:8090']

  - job_name: 'enrichment'
    static_configs:
      - targets: ['enrichment:8091']
